### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by cjcameron92** [TheMite-Server/TMCore#1]
Performance time issue with database. Login remove but is slow when checking if user is banned and chat is slow checking if user is muted. 

Permissions do not sync properly with the user depending on their rank

Setting a players rank even if they're offline needs to be done.

We also need to add a command to add a player a specific permission for an individual

**Comment by Turpster** [comment]
You have kind of added for different separate issues into one issue, please try and conveniently separate these.

**Comment by Turpster** [comment]
I'll separate these, one moment.
